<?php
/*
	
	FRAMEWORK INITIALIZATION
	
	This file loads the core framework which handles everything. 
	
	DO NOT EDIT THIS FILE.

*/

	require_once(TEMPLATEPATH . "/core/core.init.php");
	
	add_action('admin_menu','my_admin_menu');
	function my_admin_menu() {
		rename_admin_menu_section('Ecart','Shopping Cart');
	}
	